language: node_js

node_js:
  - '6'

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install
 
script:
  - npm run build && npm test